
title: Red Hat Partner Bootcamp
description: Presentations from Red Hat Partner Bootcamp
url: "http://rhepds.github.io/bootcamp"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
logo: "img/rhepds.png"
aux_links:
  "Main Page":
    - "//rhepds.github.io"
  "Red Hat Partner Page":
    - "//www.redhat-partner.com"
aux_links_new_tab: true
search_enabled: false
