
title: SAP Install
description: How to Use Ansible Collection `community.sap_install`
url: "http://rhepds.github.io/bootcamp"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
# https://just-the-docs.github.io/just-the-docs/docs/configuration/
logo: "assets/img/logo-RHAAP.png"
aux_links:
  "Main Page":
    - "//rhepds.github.io"
  "Playbook examples":
    - "//github.com/sap-linuxlab/demo.sap_install"
aux_links_new_tab: true

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable Mermaid Diagrams: https://mermaid-js.github.io/mermaid/#/
#mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  #version: "9.2.2"

